// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: pkg/ws-proxy/schema/scene.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SceneIndex       int32  `protobuf:"varint,2,opt,name=sceneIndex,proto3" json:"sceneIndex,omitempty"`
	IsCurrentProgram bool   `protobuf:"varint,3,opt,name=is_current_program,json=isCurrentProgram,proto3" json:"is_current_program,omitempty"`
}

func (x *Scene) Reset() {
	*x = Scene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_pkg_ws_proxy_schema_scene_proto_rawDescGZIP(), []int{0}
}

func (x *Scene) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scene) GetSceneIndex() int32 {
	if x != nil {
		return x.SceneIndex
	}
	return 0
}

func (x *Scene) GetIsCurrentProgram() bool {
	if x != nil {
		return x.IsCurrentProgram
	}
	return false
}

type ListSceneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32 `protobuf:"varint,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
}

func (x *ListSceneRequest) Reset() {
	*x = ListSceneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSceneRequest) ProtoMessage() {}

func (x *ListSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSceneRequest.ProtoReflect.Descriptor instead.
func (*ListSceneRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ws_proxy_schema_scene_proto_rawDescGZIP(), []int{1}
}

func (x *ListSceneRequest) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type ListSceneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scene []*Scene `protobuf:"bytes,1,rep,name=scene,proto3" json:"scene,omitempty"`
}

func (x *ListSceneResponse) Reset() {
	*x = ListSceneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSceneResponse) ProtoMessage() {}

func (x *ListSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSceneResponse.ProtoReflect.Descriptor instead.
func (*ListSceneResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ws_proxy_schema_scene_proto_rawDescGZIP(), []int{2}
}

func (x *ListSceneResponse) GetScene() []*Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

type MoveSceneToNextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32 `protobuf:"varint,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
}

func (x *MoveSceneToNextRequest) Reset() {
	*x = MoveSceneToNextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveSceneToNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSceneToNextRequest) ProtoMessage() {}

func (x *MoveSceneToNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ws_proxy_schema_scene_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSceneToNextRequest.ProtoReflect.Descriptor instead.
func (*MoveSceneToNextRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ws_proxy_schema_scene_proto_rawDescGZIP(), []int{3}
}

func (x *MoveSceneToNextRequest) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

var File_pkg_ws_proxy_schema_scene_proto protoreflect.FileDescriptor

var file_pkg_ws_proxy_schema_scene_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x05, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x73, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x69, 0x73, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x22, 0x2c, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x22,
	0x38, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x32, 0x0a, 0x16, 0x4d, 0x6f, 0x76,
	0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x6f, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x32, 0x9f, 0x01,
	0x0a, 0x0c, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0f, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x54,
	0x6f, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x1e, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x54, 0x6f, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x64, 0x61, 0x79, 0x73, 0x6a, 0x70, 0x2f,
	0x63, 0x6e, 0x64, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x77, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ws_proxy_schema_scene_proto_rawDescOnce sync.Once
	file_pkg_ws_proxy_schema_scene_proto_rawDescData = file_pkg_ws_proxy_schema_scene_proto_rawDesc
)

func file_pkg_ws_proxy_schema_scene_proto_rawDescGZIP() []byte {
	file_pkg_ws_proxy_schema_scene_proto_rawDescOnce.Do(func() {
		file_pkg_ws_proxy_schema_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ws_proxy_schema_scene_proto_rawDescData)
	})
	return file_pkg_ws_proxy_schema_scene_proto_rawDescData
}

var file_pkg_ws_proxy_schema_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_ws_proxy_schema_scene_proto_goTypes = []interface{}{
	(*Scene)(nil),                  // 0: schema.Scene
	(*ListSceneRequest)(nil),       // 1: schema.ListSceneRequest
	(*ListSceneResponse)(nil),      // 2: schema.ListSceneResponse
	(*MoveSceneToNextRequest)(nil), // 3: schema.MoveSceneToNextRequest
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_pkg_ws_proxy_schema_scene_proto_depIdxs = []int32{
	0, // 0: schema.ListSceneResponse.scene:type_name -> schema.Scene
	1, // 1: schema.SceneService.ListScene:input_type -> schema.ListSceneRequest
	3, // 2: schema.SceneService.MoveSceneToNext:input_type -> schema.MoveSceneToNextRequest
	2, // 3: schema.SceneService.ListScene:output_type -> schema.ListSceneResponse
	4, // 4: schema.SceneService.MoveSceneToNext:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_ws_proxy_schema_scene_proto_init() }
func file_pkg_ws_proxy_schema_scene_proto_init() {
	if File_pkg_ws_proxy_schema_scene_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ws_proxy_schema_scene_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ws_proxy_schema_scene_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSceneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ws_proxy_schema_scene_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSceneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ws_proxy_schema_scene_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveSceneToNextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ws_proxy_schema_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ws_proxy_schema_scene_proto_goTypes,
		DependencyIndexes: file_pkg_ws_proxy_schema_scene_proto_depIdxs,
		MessageInfos:      file_pkg_ws_proxy_schema_scene_proto_msgTypes,
	}.Build()
	File_pkg_ws_proxy_schema_scene_proto = out.File
	file_pkg_ws_proxy_schema_scene_proto_rawDesc = nil
	file_pkg_ws_proxy_schema_scene_proto_goTypes = nil
	file_pkg_ws_proxy_schema_scene_proto_depIdxs = nil
}
